package:
  name: netgen
  version: 6.2

source:
  path: ../..

build:

build:
  script_env:
    - CC
    - CXX

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - oce ==0.17.2
    - ninja
    - cmake

  run:
    - oce ==0.17.2

about:
  home: https://sourceforge.net/projects/netgen-mesher/
  license: LGPL
  summary: NETGEN is an automatic mesh generator
